
import argparse

parser = argparse.ArgumentParser(description='**CLDyN-RSC**')
parser.add_argument('--train_save_dir', default='./checkpoints', type=str)
parser.add_argument('--vfn_ckpt_dir', default="...", type=str)
parser.add_argument('--yolov5_ckpt_dir', default="...", type=str)
parser.add_argument('--yolov5_data_yaml', default="...", type=str)
parser.add_argument('--segformer_config', default="...", type=str)
parser.add_argument('--segformer_test_config', default="...", type=str)
parser.add_argument('--segformer_ckpt_dir', default="...", type=str)
parser.add_argument('--ctdnet_ckpt_dir', default="...", type=str)
parser.add_argument('--od_dataset_dir', default="...", type=str)
parser.add_argument('--sod_dataset_dir', default="...", type=str)
parser.add_argument('--save_image_num', default=8, type=int)
parser.add_argument('--save_model_num', default=5, type=int)
parser.add_argument('--lam', type=int, default=0.5)
parser.add_argument('--embed_dim', type=int, default=256)
parser.add_argument('--vector_num', type=int, default=32)
parser.add_argument('--filter_num', type=int, default=4)
parser.add_argument('--set_num', type=int, default=4)
parser.add_argument('--inC', type=int, default=8)
parser.add_argument('--num_blocks', type=int, default=2)
parser.add_argument('--batch_size', dest='batch_size', default=4, type=int)
parser.add_argument('--LR', type=float, default=0.01)
parser.add_argument('--Epoch', type=float, default=50)
args = parser.parse_args()